apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NsNameRegex
metadata:
  name: system-like-namespaces
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    #   This parameter is useful for debugging, but can leak sensitive information
    #   to an end user. Use with caution.
    # display_invalid: true
    errstring: "System-like namespace names are not allowed."
    regexes:
    - 'system'
    - 'kube'
    - 'vmware'
    - 'k8'
    - 'tanzu'
    - 'avi'
    # Here's an invalid regex for testing
    # - 'foo(bar'
