#!/usr/bin/env bash

set -euo pipefail

[ -n "${NAMESPACE:-}" ] || { >&2 echo "Please set the \"NAMESPACE\" environment variable to run this script."
			     >&2 echo "Example: NAMESPACE=sonobouy ${0}"; exit 1; }
kubectl proxy &
kubectl get namespace $NAMESPACE -o json |jq '.spec = {"finalizers":[]}' >temp.json
curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
